ruleset_version: "0.1"
repos:
  omnibase_core:
    forbids:
      - "^from\\s+omniagent\\b"
      - "^from\\s+omnimcp\\b"
      - "^import\\s+omniagent\\b"
      - "^import\\s+omnimcp\\b"
  omniagent:
    forbids:
      - "^from\\s+omnibase_core\\b"
      - "^from\\s+omnibase_infra\\b"
      - "^import\\s+omnibase_core\\b"
      - "^import\\s+omnibase_infra\\b"
  omnimcp:
    forbids:
      - "^from\\s+omnibase_core\\b"
      - "^import\\s+omnibase_core\\b"
  omnimemory:
    forbids:
      - "^from\\s+omnibase_core\\b"
      - "^import\\s+omnibase_core\\b"
  omnibase_spi:
    forbids:
      - "^import\\s+(os|pathlib|sqlite3)\\b"
      - "^from\\s+(os|pathlib|sqlite3)\\b"
      - "^from\\s+(requests|httpx)\\b"
      - "^import\\s+(requests|httpx)\\b"