repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

# Temporarily disabled flake8 until import and line length issues are resolved
# - repo: https://github.com/pycqa/flake8
#   rev: 7.0.0
#   hooks:
#     - id: flake8
#       args: [--max-line-length=120, --ignore=E203,W503]

# Temporarily disabled mypy until type errors are resolved
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.8.0
#   hooks:
#     - id: mypy
#       additional_dependencies: [pydantic]
#       args: [--strict, --ignore-missing-imports]