repos:
  - repo: local
    hooks:
      - id: validate-no-fallbacks
        name: Validate no fallback patterns
        entry: ./scripts/validate-no-fallbacks.sh
        language: script
        files: "src/.*\\.py$"
        always_run: true
        pass_filenames: false
        stages: [commit]

      - id: validate-spi-purity
        name: Validate SPI purity
        entry: ./scripts/validate-spi-purity.sh
        language: script
        files: "src/.*\\.py$"
        always_run: true
        pass_filenames: false
        stages: [commit]

      - id: validate-no-deprecated
        name: Validate no deprecated patterns
        entry: ./scripts/validate-no-deprecated.sh
        language: script
        files: "src/.*\\.py$"
        always_run: true
        pass_filenames: false
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --ignore=E203,W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic]
        args: [--strict, --ignore-missing-imports]