"""
Error type enumeration for ONEX Foundation Architecture.

Defines standardized error types for comprehensive error handling and categorization.
"""

from enum import Enum


class EnumErrorType(str, Enum):
    """Standardized error types for system-wide error handling."""

    # Validation errors
    VALIDATION = "VALIDATION"
    SCHEMA_VALIDATION = "SCHEMA_VALIDATION"
    DATA_VALIDATION = "DATA_VALIDATION"
    TYPE_VALIDATION = "TYPE_VALIDATION"

    # Authentication and authorization errors
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    # Resource errors
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"

    # Network and connectivity errors
    NETWORK = "NETWORK"
    CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
    CONNECTION_REFUSED = "CONNECTION_REFUSED"
    DNS_RESOLUTION = "DNS_RESOLUTION"

    # Database errors
    DATABASE = "DATABASE"
    DATABASE_CONNECTION = "DATABASE_CONNECTION"
    DATABASE_TIMEOUT = "DATABASE_TIMEOUT"
    DATABASE_CONSTRAINT = "DATABASE_CONSTRAINT"

    # Cache errors
    CACHE = "CACHE"
    CACHE_MISS = "CACHE_MISS"
    CACHE_FULL = "CACHE_FULL"
    CACHE_TIMEOUT = "CACHE_TIMEOUT"

    # Configuration errors
    CONFIGURATION = "CONFIGURATION"
    MISSING_CONFIGURATION = "MISSING_CONFIGURATION"
    INVALID_CONFIGURATION = "INVALID_CONFIGURATION"

    # System errors
    SYSTEM = "SYSTEM"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"

    # Business logic errors
    BUSINESS_LOGIC = "BUSINESS_LOGIC"
    INVALID_OPERATION = "INVALID_OPERATION"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"

    # External service errors
    EXTERNAL_SERVICE = "EXTERNAL_SERVICE"
    THIRD_PARTY_ERROR = "THIRD_PARTY_ERROR"
    API_ERROR = "API_ERROR"
